const storageKeys = {
  leads: "grainConferenceLeads",
  settings: "grainConferenceSettings",
};

const DEFAULT_MODEL = "gpt-4.1-mini";
const SEPARATOR = " - ";
const CONFERENCES_PER_PAGE = 9;
const CLUSTERS_PER_PAGE = 3;
const LEADS_PER_PAGE = 4;

const leadSignals = [
  "Cross-border payments",
  "PSP or merchant acquiring",
  "Travel wholesaler or OTA",
  "Corporate treasury",
  "Marketplace or SaaS finance",
  "Low fit / partner curiosity",
];

const leadStages = [
  "Quick booth scan",
  "Problem confirmed",
  "Budget or owner identified",
  "Asked for follow-up",
  "Existing opportunity",
];

const signalScores = {
  "Cross-border payments": 25,
  "PSP or merchant acquiring": 23,
  "Travel wholesaler or OTA": 22,
  "Corporate treasury": 24,
  "Marketplace or SaaS finance": 16,
  "Low fit / partner curiosity": 6,
};

const stageScores = {
  "Quick booth scan": 5,
  "Problem confirmed": 16,
  "Budget or owner identified": 25,
  "Asked for follow-up": 22,
  "Existing opportunity": 28,
};

const conferences = [
  {
    id: "money2020-usa-2026",
    name: "Money20/20 USA",
    startDate: "2026-10-18",
    endDate: "2026-10-21",
    city: "Las Vegas",
    country: "USA",
    region: "North America",
    vertical: "Fintech / Payments",
    audience: 11000,
    personas: ["PSP", "Fintech", "Banking", "Cross-border payments", "Payment leaders", "CFO / Finance"],
    estimatedBuyerDensity: 9,
    fxFit: 9,
    travelFit: 3,
    source: "https://us.money2020.com/",
    sourceLabel: "Money20/20 USA official page",
    reason: "Money20/20 reports 11,000+ senior attendees from 3,400+ companies, including banks, payment companies, and fintechs. Strong room for international payments and multi-currency exposure.",
  },
  {
    id: "wtm-london-2026",
    name: "WTM London",
    startDate: "2026-11-03",
    endDate: "2026-11-05",
    city: "London",
    country: "United Kingdom",
    region: "Europe",
    vertical: "Travel / Tourism",
    audience: 46000,
    personas: ["Travel wholesalers", "Tour operators", "OTAs", "DMCs", "Travel technology", "Travel buyers"],
    estimatedBuyerDensity: 7,
    fxFit: 8,
    travelFit: 10,
    source: "https://www.wtm.com/london/en-gb.html",
    sourceLabel: "WTM London official page",
    reason: "WTM reports 46,000+ attendees and 5,500+ buyers. Tour operators, OTAs, DMCs, and accommodation businesses frequently collect and pay in multiple currencies.",
  },
  {
    id: "phocuswright-conference-2026",
    name: "The Phocuswright Conference",
    startDate: "2026-11-17",
    endDate: "2026-11-19",
    city: "Fort Lauderdale",
    country: "USA",
    region: "North America",
    vertical: "Travel Tech",
    audience: 1200,
    personas: ["OTAs", "Travel technology", "Hotels", "Airlines", "Travel finance", "Tour operators", "Travel executives"],
    estimatedBuyerDensity: 9,
    fxFit: 8,
    travelFit: 10,
    source: "https://www.phocuswrightconference.com/",
    sourceLabel: "Phocuswright official page",
    reason: "Concentrated travel decision-maker audience with a high share of C-level and VP-level attendees. Smaller event, but unusually relevant for Grain's travel vertical.",
  },
  {
    id: "imtm-tel-aviv-2027",
    name: "IMTM - International Mediterranean Tourism Market",
    startDate: "2027-02-16",
    endDate: "2027-02-17",
    city: "Tel Aviv",
    country: "Israel",
    region: "Middle East",
    vertical: "Travel / Tourism",
    audience: 17000,
    personas: ["Travel wholesalers", "Tour operators", "Travel agencies", "DMCs", "Hotels", "Travel buyers"],
    estimatedBuyerDensity: 7,
    fxFit: 8,
    travelFit: 10,
    source: "https://www.imtm-telaviv.com/",
    sourceLabel: "IMTM official page",
    reason: "Israel's flagship B2B tourism marketplace. Travel wholesalers, agencies, and international tourism companies commonly manage multi-currency supplier and customer flows.",
  },
  {
    id: "fintech-meetup-2027",
    name: "Fintech Meetup",
    startDate: "2027-02-22",
    endDate: "2027-02-24",
    city: "Las Vegas",
    country: "USA",
    region: "North America",
    vertical: "Fintech / Financial Services",
    audience: 5000,
    personas: ["Fintech", "Banks", "Payment companies", "Financial institutions", "Merchants", "Fintech founders"],
    estimatedBuyerDensity: 9,
    fxFit: 8,
    travelFit: 3,
    source: "https://fintechmeetup.com/",
    sourceLabel: "Fintech Meetup official page",
    reason: "Curated double-opt-in meeting format with banks, merchants, fintechs, and financial institutions. Useful for targeted meetings rather than booth-only scans.",
  },
  {
    id: "markethub-asia-2027",
    name: "MarketHub Asia",
    startDate: "2027-02-23",
    endDate: "2027-02-26",
    city: "Cebu",
    country: "Philippines",
    region: "Asia Pacific",
    vertical: "Travel Wholesale / Travel Tech",
    audience: null,
    personas: ["Travel wholesalers", "Wholesale distributors", "Global travel agencies", "Hotels", "Travel technology", "DMCs"],
    estimatedBuyerDensity: 9,
    fxFit: 9,
    travelFit: 10,
    source: "https://www.hbxgroup.com/markethub",
    sourceLabel: "HBX Group MarketHub page",
    reason: "B2B travel event for wholesale distributors, global travel agencies, hoteliers, and travel trade decision-makers with frequent cross-currency settlement needs.",
  },
  {
    id: "mpe-2027",
    name: "Merchant Payments Ecosystem (MPE)",
    startDate: "2027-03-09",
    endDate: "2027-03-11",
    city: "Berlin",
    country: "Germany",
    region: "Europe",
    vertical: "Payments / Merchant Payments",
    audience: 1600,
    personas: ["PSP", "Acquirer", "Fintech", "Merchant", "Payment provider", "Payment orchestration"],
    estimatedBuyerDensity: 10,
    fxFit: 9,
    travelFit: 3,
    source: "https://www.merchantpaymentsecosystem.com/",
    sourceLabel: "MPE official page",
    reason: "Very concentrated payments audience. Particularly attractive for Grain's PSP, acquirer, payment orchestration, and cross-border payments ICP.",
  },
  {
    id: "itb-berlin-2027",
    name: "ITB Berlin",
    startDate: "2027-03-16",
    endDate: "2027-03-18",
    city: "Berlin",
    country: "Germany",
    region: "Europe",
    vertical: "Travel / Tourism",
    audience: 97000,
    personas: ["Travel wholesalers", "Tour operators", "OTAs", "Hotels", "Travel technology", "DMCs", "Travel buyers"],
    estimatedBuyerDensity: 6,
    fxFit: 8,
    travelFit: 10,
    source: "https://www.itb.com/en",
    sourceLabel: "ITB Berlin official page",
    reason: "Massive B2B travel marketplace. International tour operators, accommodation providers, and travel platforms can have significant multi-currency receivables and supplier payments.",
  },
  {
    id: "eurofinance-west-coast-2027",
    name: "EuroFinance Treasury & Cash Management Summit San Francisco",
    startDate: "2027-03-16",
    endDate: "2027-03-17",
    city: "San Francisco",
    country: "USA",
    region: "North America",
    vertical: "Treasury / FX",
    audience: null,
    personas: ["Corporate treasurers", "CFO / Finance", "FX risk managers", "Cash management", "Scale-ups", "Multinational companies"],
    estimatedBuyerDensity: 10,
    fxFit: 10,
    travelFit: 1,
    source: "https://www.eurofinance.com/treasury-cash-management-summit-west-coast/",
    sourceLabel: "EuroFinance West Coast official page",
    reason: "Extremely direct Grain fit for corporate treasurers managing cross-border cash flow, real-time payments, liquidity, and FX risk.",
  },
  {
    id: "international-payments-conference-2027",
    name: "International Payments Conference (IPC)",
    startDate: "2027-04-05",
    endDate: "2027-04-07",
    city: "Washington, D.C.",
    country: "USA",
    region: "North America",
    vertical: "Payments / Fintech",
    audience: null,
    personas: ["Payment companies", "Fintech", "Payment executives", "Financial institutions", "Payments compliance", "Payment technology"],
    estimatedBuyerDensity: 8,
    fxFit: 8,
    travelFit: 1,
    source: "https://www.ipa.org/ipc.html",
    sourceLabel: "Innovative Payments Association IPC page",
    reason: "Specialized payments gathering focused on payment innovation, regulation, and companies building payment products.",
  },
  {
    id: "smarter-faster-payments-2027",
    name: "Smarter Faster Payments 2027",
    startDate: "2027-04-11",
    endDate: "2027-04-14",
    city: "Washington, D.C.",
    country: "USA",
    region: "North America",
    vertical: "Payments",
    audience: null,
    personas: ["Payment companies", "Banks", "Fintech", "Payment strategists", "Finance teams", "Payment technology"],
    estimatedBuyerDensity: 8,
    fxFit: 7,
    travelFit: 1,
    source: "https://payments.nacha.org/",
    sourceLabel: "Nacha Smarter Faster Payments page",
    reason: "Payments-industry conference bringing together payments experts, influencers, and fintech solution providers.",
  },
  {
    id: "transact-2027",
    name: "TRANSACT 2027",
    startDate: "2027-04-19",
    endDate: "2027-04-21",
    city: "Las Vegas",
    country: "USA",
    region: "North America",
    vertical: "Payments / Merchant Acquiring",
    audience: null,
    personas: ["PSP", "Payment processors", "Acquirers", "Fintech", "Platforms", "Merchants", "Payment executives"],
    estimatedBuyerDensity: 9,
    fxFit: 9,
    travelFit: 2,
    source: "https://etatransact.com/register/",
    sourceLabel: "TRANSACT official page",
    reason: "Strong payments prospecting opportunity bringing together issuers, processors, fintech founders, platforms, and merchants.",
  },
  {
    id: "markethub-europe-2027",
    name: "MarketHub Europe",
    startDate: "2027-04-20",
    endDate: "2027-04-23",
    city: "Rhodes",
    country: "Greece",
    region: "Europe",
    vertical: "Travel Wholesale / Travel Tech",
    audience: null,
    personas: ["Travel wholesalers", "Wholesale distributors", "Global travel agencies", "Hotels", "Travel technology", "Tourism decision-makers"],
    estimatedBuyerDensity: 10,
    fxFit: 10,
    travelFit: 10,
    source: "https://www.hbxgroup.com/markethub",
    sourceLabel: "HBX Group MarketHub page",
    reason: "Highly targeted B2B travel distribution event with businesses that often have meaningful cross-border currency exposure.",
  },
  {
    id: "pay360-2027",
    name: "PAY360",
    startDate: "2027-04-21",
    endDate: "2027-04-22",
    city: "London",
    country: "United Kingdom",
    region: "Europe",
    vertical: "Payments",
    audience: 7000,
    personas: ["PSP", "Payments executives", "Banks", "Fintech", "Payment infrastructure", "Merchants"],
    estimatedBuyerDensity: 9,
    fxFit: 9,
    travelFit: 2,
    source: "https://pay360event.com/",
    sourceLabel: "PAY360 official page",
    reason: "Dedicated payments event with a high concentration of senior payments professionals, fintechs, banks, payment infrastructure teams, and decision-makers.",
  },
  {
    id: "money2020-asia-2027",
    name: "Money20/20 Asia",
    startDate: "2027-04-27",
    endDate: "2027-04-29",
    city: "Bangkok",
    country: "Thailand",
    region: "Asia Pacific",
    vertical: "Fintech / Payments",
    audience: 4000,
    personas: ["PSP", "Fintech", "Banking", "Cross-border payments", "Payment leaders", "Financial institutions"],
    estimatedBuyerDensity: 9,
    fxFit: 9,
    travelFit: 3,
    source: "https://www.money2020.com/",
    sourceLabel: "Money20/20 official page",
    reason: "Asia-Pacific edition of Money20/20. The region contains significant cross-border commerce, payment, and currency flows.",
  },
  {
    id: "payments-canada-summit-2027",
    name: "Payments Canada SUMMIT",
    startDate: "2027-05-04",
    endDate: "2027-05-06",
    city: "Toronto",
    country: "Canada",
    region: "North America",
    vertical: "Payments / Financial Infrastructure",
    audience: 2000,
    personas: ["Payment companies", "Banks", "Fintech", "Payment infrastructure", "Payment executives", "Financial institutions"],
    estimatedBuyerDensity: 8,
    fxFit: 8,
    travelFit: 1,
    source: "https://www.thesummit.ca/",
    sourceLabel: "Payments Canada SUMMIT official page",
    reason: "Strong concentration of payments infrastructure, financial institutions, and fintech decision-makers.",
  },
  {
    id: "saastr-ai-annual-2027",
    name: "SaaStr AI Annual",
    startDate: "2027-05-11",
    endDate: "2027-05-12",
    city: "San Mateo",
    country: "USA",
    region: "North America",
    vertical: "SaaS / B2B Technology",
    audience: 10000,
    personas: ["SaaS founders", "CFO / Finance", "CEOs", "B2B executives", "Marketplace leaders", "Scale-ups"],
    estimatedBuyerDensity: 6,
    fxFit: 6,
    travelFit: 1,
    source: "https://www.saastrannual.com/",
    sourceLabel: "SaaStr official page",
    reason: "Useful for fast-growing SaaS and marketplace companies expanding internationally and developing meaningful FX exposure, but less concentrated than payments or treasury events.",
  },
  {
    id: "phocuswright-europe-2027",
    name: "Phocuswright Europe",
    startDate: "2027-05-24",
    endDate: "2027-05-26",
    city: "London",
    country: "United Kingdom",
    region: "Europe",
    vertical: "Travel Tech",
    audience: null,
    personas: ["OTAs", "Travel technology", "Travel platforms", "Hotels", "Travel executives", "Travel investors", "Tour operators"],
    estimatedBuyerDensity: 9,
    fxFit: 8,
    travelFit: 10,
    source: "https://www.phocuswright.com/events",
    sourceLabel: "Phocuswright events page",
    reason: "Strong concentration of senior digital travel, distribution, and technology decision-makers.",
  },
  {
    id: "money2020-europe-2027",
    name: "Money20/20 Europe",
    startDate: "2027-06-08",
    endDate: "2027-06-10",
    city: "Amsterdam",
    country: "Netherlands",
    region: "Europe",
    vertical: "Fintech / Payments",
    audience: 7400,
    personas: ["PSP", "Fintech", "Banking", "Cross-border payments", "Payment leaders", "Financial institutions"],
    estimatedBuyerDensity: 10,
    fxFit: 10,
    travelFit: 3,
    source: "https://europe.money2020.com/",
    sourceLabel: "Money20/20 Europe official page",
    reason: "Excellent concentration of European payments and fintech prospects with cross-border currency exposure.",
  },
  {
    id: "traveltech-show-2027",
    name: "TravelTech Show",
    startDate: "2027-06-23",
    endDate: "2027-06-24",
    city: "London",
    country: "United Kingdom",
    region: "Europe",
    vertical: "Travel Tech",
    audience: 700,
    personas: ["Travel technology buyers", "OTAs", "Tour operators", "Travel platforms", "Payments", "Travel finance"],
    estimatedBuyerDensity: 9,
    fxFit: 8,
    travelFit: 10,
    source: "https://traveltech-show.com/",
    sourceLabel: "TravelTech Show official page",
    reason: "Smaller but highly targeted travel technology event with potentially high buyer density for Grain.",
  },
  {
    id: "sibos-2027",
    name: "Sibos",
    startDate: "2027-09-20",
    endDate: "2027-09-23",
    city: "Singapore",
    country: "Singapore",
    region: "Asia Pacific",
    vertical: "Banking / Payments / Financial Infrastructure",
    audience: 12500,
    personas: ["Banks", "Payments", "Transaction banking", "Fintech", "Treasury", "Cross-border payments", "FX"],
    estimatedBuyerDensity: 9,
    fxFit: 10,
    travelFit: 2,
    source: "https://www.sibos.com/about/future-sibos",
    sourceLabel: "Sibos future events page",
    reason: "Highly concentrated gathering of banks, transaction banking teams, payment infrastructure providers, and fintechs. Strong cross-border payments and FX relevance.",
  },
  {
    id: "iftm-paris-2027",
    name: "IFTM - International & French Travel Market",
    startDate: "2027-10-05",
    endDate: "2027-10-07",
    city: "Paris",
    country: "France",
    region: "Europe",
    vertical: "Travel / Tourism",
    audience: 34638,
    personas: ["Travel agencies", "Tour operators", "Travel wholesalers", "Travel managers", "Travel technology", "MICE buyers", "Travel purchasing managers"],
    estimatedBuyerDensity: 7,
    fxFit: 8,
    travelFit: 10,
    source: "https://www.iftm.fr/en-gb.html",
    sourceLabel: "IFTM official page",
    reason: "Large B2B travel trade show with a significant travel-agency audience and many businesses exposed to international supplier and customer currencies.",
  },
  {
    id: "eurofinance-international-2027",
    name: "EuroFinance International Treasury Management",
    startDate: "2027-10-06",
    endDate: "2027-10-08",
    city: "Amsterdam",
    country: "Netherlands",
    region: "Europe",
    vertical: "Treasury / FX",
    audience: 2700,
    personas: ["Corporate treasurer", "CFO / Finance", "FX risk", "Cash management", "Banks", "Treasury technology"],
    estimatedBuyerDensity: 10,
    fxFit: 10,
    travelFit: 1,
    source: "https://www.eurofinance.com/international-treasury-event/",
    sourceLabel: "EuroFinance International Treasury page",
    reason: "Exceptionally strong direct fit for Grain, bringing together senior treasury professionals responsible for FX risk, liquidity, cross-border payments, and treasury transformation.",
  },
];

const conferenceOverrides = {
  "Money20/20 USA": {
    source: "https://us.money2020.com/",
    sourceLabel: "Official event page",
    conferenceURL: "https://us.money2020.com/",
    notes: "One of the strongest broad fintech events for Grain. Money20/20 reports 11,000+ senior attendees from 3,400+ companies, including banks, payment companies and fintechs. Strong opportunity to reach companies processing international payments and managing multi-currency exposure.",
    travelFit: 5,
  },
  "WTM London": {
    source: "https://www.wtm.com/london/en-gb/visit/prepare-to-visit.html",
    sourceLabel: "Official event page",
    conferenceURL: "https://www.wtm.com/london/en-gb.html",
    notes: "WTM reports 46,000+ attendees and 5,500+ buyers. Particularly relevant to Grain because tour operators, OTAs, DMCs and accommodation businesses frequently collect and pay in multiple currencies, creating structural FX exposure.",
  },
  "The Phocuswright Conference": {
    source: "https://www.phocuswright.com/events",
    sourceLabel: "Official Phocuswright events page",
    conferenceURL: "https://www.phocuswrightconference.com/",
    notes: "Highly concentrated travel decision-maker audience. Approximately 65% of attendees are C-level or VP-level, making the smaller audience unusually valuable for Grain.",
  },
  "IMTM - International Mediterranean Tourism Market": {
    source: "https://www.imtm-telaviv.com/",
    sourceLabel: "Official event page",
    conferenceURL: "https://www.imtm-telaviv.com/",
    notes: "Israel's flagship B2B tourism marketplace. Travel wholesalers, agencies and international tourism companies commonly manage multi-currency supplier and customer flows, making this relevant to Grain.",
  },
  "Fintech Meetup": {
    source: "https://fintechmeetup.com/2027-agenda?day=2027-02-22",
    sourceLabel: "Official event agenda",
    conferenceURL: "https://fintechmeetup.com/",
    notes: "Strong prospecting event because its format is built around curated double-opt-in meetings. It brings together banks, merchants, fintechs and financial institutions.",
    travelFit: 4,
  },
  "MarketHub Asia": {
    source: "https://www.hbxgroup.com/markethub",
    sourceLabel: "Official HBX Group event page",
    conferenceURL: "https://www.hbxgroup.com/markethub",
    notes: "B2B travel event bringing together wholesale distributors, global travel agencies, hoteliers and other travel trade decision-makers. These businesses frequently settle inventory and bookings across currencies.",
  },
  "Merchant Payments Ecosystem (MPE)": {
    source: "https://www.merchantpaymentsecosystem.com/attend/",
    sourceLabel: "Official MPE 2027 attendee page",
    conferenceURL: "https://www.merchantpaymentsecosystem.com/",
    notes: "Very concentrated payments audience. Particularly attractive for Grain's PSP and cross-border payments ICP.",
    travelFit: 4,
  },
  "ITB Berlin": {
    source: "https://www.itb.com/en",
    sourceLabel: "Official event page",
    conferenceURL: "https://www.itb.com/en",
    notes: "Massive B2B travel marketplace. International tour operators, accommodation providers and travel platforms can have significant multi-currency receivables and supplier payments.",
  },
  "EuroFinance Treasury & Cash Management Summit San Francisco": {
    source: "https://www.eurofinance.com/treasury-cash-management-summit-west-coast/",
    sourceLabel: "Official EuroFinance event page",
    conferenceURL: "https://www.eurofinance.com/treasury-cash-management-summit-west-coast/",
    notes: "Extremely direct Grain fit. The event serves corporate treasurers at scale-ups and global enterprises managing cross-border cash flow, real-time payments, liquidity and FX risk.",
    travelFit: 2,
  },
  "International Payments Conference (IPC)": {
    source: "https://www.ipa.org/ipc-445214.html",
    sourceLabel: "Official Innovative Payments Association event page",
    conferenceURL: "https://www.ipa.org/ipc.html",
    notes: "Specialized payments gathering focused on payment innovation, regulation and companies building payment products.",
    travelFit: 2,
  },
  "Smarter Faster Payments 2027": {
    source: "https://www.nacha.org/events/smarter-faster-payments-2027",
    sourceLabel: "Official Nacha event page",
    conferenceURL: "https://payments.nacha.org/",
    notes: "Payments-industry conference bringing together payments experts, influencers and fintech solution providers.",
    travelFit: 2,
  },
  "TRANSACT 2027": {
    source: "https://etatransact.com/register/",
    sourceLabel: "Official TRANSACT registration and event details",
    conferenceURL: "https://transactshow.com/",
    notes: "Strong payments prospecting opportunity bringing together issuers, processors, fintech founders, platforms and merchants.",
    travelFit: 3,
  },
  "MarketHub Europe": {
    source: "https://www.hbxgroup.com/markethub",
    sourceLabel: "Official HBX Group event page",
    conferenceURL: "https://www.hbxgroup.com/markethub",
    notes: "Highly targeted B2B travel distribution event with businesses that frequently have significant cross-border currency exposure.",
  },
  "PAY360": {
    source: "https://pay360event.com/",
    sourceLabel: "Official event page",
    conferenceURL: "https://pay360event.com/",
    notes: "Dedicated payments event with a high concentration of senior payments professionals and decision-makers.",
    travelFit: 3,
  },
  "Money20/20 Asia": {
    source: "https://asia.money2020.com/attend",
    sourceLabel: "Official Money20/20 event page",
    conferenceURL: "https://asia.money2020.com/",
    audience: 5000,
    notes: "Asia-Pacific edition of Money20/20. Particularly interesting for Grain because the region contains significant cross-border commerce, payment and currency flows.",
    travelFit: 5,
  },
  "Payments Canada SUMMIT": {
    source: "https://www.payments.ca/connect/annual-conference",
    sourceLabel: "Official Payments Canada event page",
    conferenceURL: "https://www.thesummit.ca/",
    notes: "Strong concentration of payments infrastructure, financial institutions and fintech decision-makers.",
    travelFit: 2,
  },
  "SaaStr AI Annual": {
    source: "https://saastr.ai/events/annual",
    sourceLabel: "Official SaaStr event information",
    conferenceURL: "https://saastrannual.com/",
    notes: "Useful for reaching fast-growing SaaS and marketplace companies expanding internationally and developing meaningful FX exposure.",
    travelFit: 2,
  },
  "Phocuswright Europe": {
    source: "https://www.phocuswright.com/events",
    sourceLabel: "Official Phocuswright events page",
    conferenceURL: "https://www.phocuswrighteurope.com/",
    notes: "Strong concentration of senior digital travel, distribution and technology decision-makers.",
  },
  "Money20/20 Europe": {
    source: "https://europe.money2020.com/",
    sourceLabel: "Official event page",
    conferenceURL: "https://europe.money2020.com/",
    notes: "Excellent concentration of European payments and fintech prospects with cross-border currency exposure.",
    travelFit: 5,
  },
  "TravelTech Show": {
    source: "https://traveltech-show.com/",
    sourceLabel: "Official event page",
    conferenceURL: "https://traveltech-show.com/",
    notes: "Smaller but highly targeted travel technology event with potentially high buyer density for Grain.",
  },
  "Sibos": {
    source: "https://www.sibos.com/about/future-sibos",
    sourceLabel: "Official Sibos future events page",
    conferenceURL: "https://www.sibos.com/",
    notes: "Highly concentrated gathering of banks, transaction banking teams, payment infrastructure providers and fintechs. Strong cross-border payments and FX relevance.",
    travelFit: 3,
  },
  "IFTM - International & French Travel Market": {
    source: "https://www.iftm.fr/",
    sourceLabel: "Official event page",
    conferenceURL: "https://www.iftm.fr/",
    notes: "Large B2B travel trade show with a significant travel-agency audience and many businesses potentially exposed to international supplier and customer currencies.",
  },
  "EuroFinance International Treasury Management": {
    source: "https://www.eurofinance.com/international-treasury-event/",
    sourceLabel: "Official event page",
    conferenceURL: "https://www.eurofinance.com/international-treasury-event/",
    notes: "Exceptionally strong direct fit for Grain, bringing together senior treasury professionals responsible for FX risk, liquidity, cross-border payments and treasury transformation.",
    travelFit: 3,
  },
};

conferences.forEach((conference) => {
  const override = conferenceOverrides[conference.name];
  if (!override) return;
  Object.assign(conference, override, { reason: override.notes });
});

const demoLeads = [
  {
    id: "lead-1",
    conferenceId: "itb-berlin-2027",
    name: "Maya Cohen",
    company: "AtlasPay Travel",
    email: "maya.cohen@atlaspay.example",
    title: "Director of Payments",
    signal: "Travel wholesaler or OTA",
    stage: "Problem confirmed",
    notes: "Large EUR and GBP supplier exposure. Wants a sharper way to protect margin without slowing bookings.",
    tags: ["FX exposure", "Travel flow"],
    createdAt: "2027-03-16T11:30:00.000Z",
  },
  {
    id: "lead-2",
    conferenceId: "wtm-london-2026",
    name: "Maya K. Cohen",
    company: "AtlasPay",
    email: "maya.cohen@atlaspay.example",
    title: "VP Payments",
    signal: "Cross-border payments",
    stage: "Asked for follow-up",
    notes: "New title. Asked for CFO-ready material and named Q4 budget review.",
    tags: ["CFO owner", "Follow up today"],
    createdAt: "2026-11-03T09:10:00.000Z",
  },
  {
    id: "lead-3",
    conferenceId: "mpe-2027",
    name: "Jonas Richter",
    company: "Northstar Acquiring",
    email: "jonas@northstar.example",
    title: "Partnerships Lead",
    signal: "PSP or merchant acquiring",
    stage: "Quick booth scan",
    notes: "Interested in partner story but no owned problem yet.",
    tags: ["Payments volume"],
    createdAt: "2027-03-09T16:45:00.000Z",
  },
  {
    id: "lead-4",
    conferenceId: "pay360-2027",
    name: "Jon Richter",
    company: "Northstar Payments",
    email: "jonas@northstar.example",
    title: "Director, Strategic Partnerships",
    signal: "PSP or merchant acquiring",
    stage: "Quick booth scan",
    notes: "Second conversation, still researching vendors. Asked broad pricing questions.",
    tags: ["Payments volume"],
    createdAt: "2027-04-21T14:05:00.000Z",
  },
];

